#!/usr/local/bin/php
<?php
/*
 *    Copyright (C) 2019 Deciso B.V.
 *    All rights reserved.
 *
 *    Redistribution and use in source and binary forms, with or without
 *    modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 *    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 *    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *    POSSIBILITY OF SUCH DAMAGE.
 */

use Phalcon\DI\FactoryDefault;
use Phalcon\Loader;

$di = new FactoryDefault();
$phalcon_config = include("/usr/local/opnsense/mvc/app/config/config.php");

$loader = new Loader();
$loader->registerDirs(
   array(
       $phalcon_config->application->controllersDir,
       $phalcon_config->application->modelsDir,
       $phalcon_config->application->libraryDir,
       __DIR__
   )
)->register();

$di->set('config', $phalcon_config);
unset($phalcon_config);

$opts = getopt('ah', array(), $optind);
$args = array_slice($argv, $optind);

if (isset($opts['h']) || empty($args[0])) {
    echo "Usage: config_import [-h] -[a] <sourceXml>\n\n";
    echo "\t-h show this help text and exit\n";
    echo "\t-a Import aliases\n";
    exit(0);
}
if (isset($opts['a'])) {
    // import and validate aliases
    $aliasImport = new \OPNsense\pfSenseImport\Alias($args[0]);
    $aliasImport->import();
    $report = $aliasImport->getReport();
    echo "inserted : {$report['inserted']}\n";
    echo "updated : {$report['updated']}\n";
    if (!empty($report['errors'])) {
        echo "import errors (per alias name):\n";
        foreach ($report['errors'] as $error) {
            echo "\t{$error['name']} : {$error['message']}\n";
        }
    }
}
