PLUGIN_NAME=		pfSenseImport
PLUGIN_VERSION=		0.3
PLUGIN_COMMENT=		Import and validate (partial) pfSense configuration data into the running configuration.
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
